using System;
using System.IO;

namespace No4.Solution
{
    public class RandomBytesFileGenerator : RandomFileGenerator
    {
        /// <summary>
        /// Overrides parent GenerateFileContent method 
        /// </summary>
        /// <param name="contentLength">Content legth</param>
        /// <returns>Generated byte array</returns>
        protected override byte[] GenerateFileContent(int contentLength)
        {
            var random = new Random();

            var fileContent = new byte[contentLength];

            random.NextBytes(fileContent);

            return fileContent;
        }

        /// <summary>
        /// Overrides parent WriteBytesToFile method
        /// </summary>
        /// <param name="fileName">File name</param>
        /// <param name="content">File content</param>
        protected override void WriteBytesToFile(string fileName, byte[] content)
        {
            if (!Directory.Exists(WorkingDirectory))
            {
                Directory.CreateDirectory(WorkingDirectory);
            }

            File.WriteAllBytes($"{WorkingDirectory}//{fileName}", content);
        }
    }
}